# Sesion 4



# 1 Reshape

In [2]:
import numpy as np
from time import time

In [3]:
x = np.arange(1,11,1)

In [4]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
x.shape

(10,)

In [6]:
np.reshape(x, (2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
np.reshape(x, (5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
np.reshape(x, (10,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [9]:
np.reshape(x, (-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [10]:
np.reshape(x, (1,10))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [11]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2. Performance

In [12]:
x = np.linspace(1, 10000000, 20000000) 
b0 = 5
b1 = 2

In [13]:
y = np.empty_like(x)

inicio = time()
for index, value in enumerate(x):
    y[index] = b0 + b1*value
fin = time()


In [14]:
print("El tiempo total es: ", fin - inicio)

El tiempo total es:  17.617624044418335


In [15]:
x = np.arange(1,6,1)
x

array([1, 2, 3, 4, 5])

In [16]:
# se usará en el proyecto, calcular el error y - y estimado

In [17]:
vect1 = np.ones_like(x).reshape((-1,1))
x_stack = x.reshape((-1,1))
A = np.hstack([vect1,x_stack])
A

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [18]:
betas = np.array([[b0], [b1]])

inicio = time()
y1 = np.matmul(A, betas)
fin = time()

print("El tiempo es; ", fin - inicio)

El tiempo es;  0.011182546615600586


In [19]:
# hasta aquí

# 3. Pandas - (Panel Data)

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data = np.random.rand(10)
data

In [ ]:
# El data Frame es un conjunto de columnas de series
pd.Series(np.random.rand(10))

In [ ]:
pd.Series(data, index=np.arange(10, 110, 10))

In [ ]:
diccionario = {'A':30,'B':60, 'C':'Hola', 'D':np.exp(5)}
diccionario

In [ ]:
pd.Series(diccionario)

In [ ]:
d = { 'columnaA': [10, 20, 30, 40],
         'columnaB': pd.Series(['abc', 10.5, 34, 'xy']),
         'columnaC': pd.Series([10.45, 89.34, 90.76, 24.89])
     }

In [ ]:
df1 = pd.DataFrame(d)

In [ ]:
df1

In [ ]:
type(df1['columnaB'])

In [ ]:
df1[['columnaA','columnaC']]

In [ ]:
df1[['columnaC','columnaA']]

In [ ]:
#extraemos información en base al nombre de la fila(index) y la columna
df1.loc[[0,1,3],['columnaC', 'columnaA']]

In [ ]:
#extraemos información en base al nombre de la fila(index) y la columna
df1.iloc[[0,1,3],[2,0]]

In [ ]:
#nueva columna
df1['nueva']= df1['columnaA'] + df1['columnaC']
df1

In [ ]:
#eliminar filas/columnas drop(indice/columna, axis (0 fila, columna 1))
#drop.nan
df1.drop(0, axis=0)

In [ ]:
"""
    afecta la original
    inplace = True --> modifica la variable original con la
    operación aplicada
"""
df1.drop(0, axis=0, inplace = True)

# 3.1 Filtros

In [ ]:
df2 = pd.DataFrame({
    'A': np.random.randint(1, 20, size=10),
    'B': np.random.randint(1, 20, size=10)
})

df2

In [ ]:
df2[df2['A'] > 10]


In [ ]:
df2['A'] >10

In [ ]:
df2[(df2['A'] > 7) & (df2['B'] < 10)]

In [ ]:
df1.loc[:,['columnaB']]

In [ ]:
df1.loc[[0,2],['columnaB']]

# 3.2 Operaciones de Agregación

In [ ]:
df = pd.DataFrame({'col1': [10,20,30,40,50,60], 
                   'col2':[1,2,3,4,5,6], 
                   'col3':['A', 'B', 'C', 'D', 'A', 'F']})

df

In [ ]:
df['col1'].sum()

In [ ]:
#axis = 0  - operación sobre columnas
#axis = 1  - operación sobre fila (indices)
df[['col1','col2']].sum(axis=1)

In [ ]:
df[['col1','col2']].sum(axis=0)

In [ ]:
#cuenta cantidad de valores, mas de uno si se repite
df['col3'].value_counts()

In [ ]:
#Cuenta cantidad de filas en la columna
df['col2'].count()

In [ ]:
#devuelve el arreglo con nombres de columnas
df['col2'].values

In [ ]:
dataset = pd.read_csv("hotel_bookings.csv")
dataset.head()

In [ ]:
dataset.shape

In [ ]:
dataset.dtypes

In [ ]:
dataset['is_canceled'].value_counts()

In [ ]:
dataset['lead_time'].value_counts()